<center><img src="redpopcorn.jpg"></center>

**Netflix**! What started in 1997 as a DVD rental service has since exploded into one of the largest entertainment and media companies.

Given the large number of movies and series available on the platform, it is a perfect opportunity to flex your exploratory data analysis skills and dive into the entertainment industry.

You work for a production company that specializes in nostalgic styles. You want to do some research on movies released in the 1990's. You'll delve into Netflix data and perform exploratory data analysis to better understand this awesome movie decade!

You have been supplied with the dataset `netflix_data.csv`, along with the following table detailing the column names and descriptions. Feel free to experiment further after submitting!

## The data
### **netflix_data.csv**
| Column | Description |
|--------|-------------|
| `show_id` | The ID of the show |
| `type` | Type of show |
| `title` | Title of the show |
| `director` | Director of the show |
| `cast` | Cast of the show |
| `country` | Country of origin |
| `date_added` | Date added to Netflix |
| `release_year` | Year of Netflix release |
| `duration` | Duration of the show in minutes |
| `description` | Description of the show |
| `genre` | Show genre |

**Step 1**: Load the Netflix dataset into a pandas DataFrame to start the analysis.

In [81]:
# Importing pandas and matplotlib
import pandas as pd
import matplotlib.pyplot as plt

# Read in the Netflix CSV as a DataFrame
netflix_df = pd.read_csv("netflix_data.csv")

**Step 2**: Get an overview of the dataset to understand its structure and the data it contains.

In [82]:
# Start coding here! Use as many cells as you like (Comment by DataCamp)
# Display the first 10 rows
netflix_df.head(10)

  show_id  ...             genre
0      s2  ...            Dramas
1      s3  ...     Horror Movies
2      s4  ...            Action
3      s5  ...            Dramas
4      s6  ...  International TV
5      s7  ...     Horror Movies
6      s8  ...            Dramas
7      s9  ...     Horror Movies
8     s10  ...     Horror Movies
9     s11  ...            Dramas

[10 rows x 11 columns]

In [83]:
# Display the last 10 rows
netflix_df.tail(10)

     show_id  ...          genre
4802   s7772  ...  Documentaries
4803   s7773  ...       Children
4804   s7774  ...  Documentaries
4805   s7775  ...    Cult Movies
4806   s7777  ...       Children
4807   s7779  ...       Comedies
4808   s7781  ...         Dramas
4809   s7782  ...       Children
4810   s7783  ...         Dramas
4811   s7784  ...         Dramas

[10 rows x 11 columns]

In [84]:
# Check dataset dtypes
netflix_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4812 entries, 0 to 4811
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       4812 non-null   object
 1   type          4812 non-null   object
 2   title         4812 non-null   object
 3   director      4812 non-null   object
 4   cast          4812 non-null   object
 5   country       4812 non-null   object
 6   date_added    4812 non-null   object
 7   release_year  4812 non-null   int64
 8   duration      4812 non-null   int64
 9   description   4812 non-null   object
 10  genre         4812 non-null   object
dtypes: int64(2), object(9)
memory usage: 413.7+ KB

In [85]:
# Display summary statistics
netflix_df.describe()

       release_year     duration
count   4812.000000  4812.000000
mean    2012.711554    99.566708
std        9.517978    30.889305
min     1942.000000     1.000000
25%     2011.000000    88.000000
50%     2016.000000    99.000000
75%     2018.000000   116.000000
max     2021.000000   253.000000

In [86]:
# Check for missing values
netflix_df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
duration        0
description     0
genre           0
dtype: int64

**Step 3**: Filter the dataset to include only movies released in the 1990s.

In [87]:
# Filter data for movies released in 1990s
movies_1990s = netflix_df[(netflix_df['release_year'] >= 1990) & (netflix_df['release_year'] < 2000)]
print(movies_1990s)

     show_id  ...           genre
6         s8  ...          Dramas
118     s167  ...          Dramas
145     s211  ...        Comedies
167     s239  ...        Comedies
194     s274  ...          Dramas
...      ...  ...             ...
4672   s7536  ...          Dramas
4689   s7571  ...  Classic Movies
4718   s7624  ...          Action
4746   s7682  ...          Action
4756   s7695  ...          Dramas

[184 rows x 11 columns]

**Step 4**: Find the most frequent movie duration in the 1990s.

In [88]:
# Determine the most frequent movie duration in the 1990s
duration = movies_1990s['duration'].mode()[0]
print('The most frequent movie duration in the 1990s is ' + str(duration) + ' minutes')

The most frequent movie duration in the 1990s is 94 minutes

Step 5: Count the number of short action movies (less than 90 minutes) released in the 1990s.

In [89]:
# Get a summary of the unique genres
print(movies_1990s['genre'].unique())

['Dramas' 'Comedies' 'Children' 'Action' 'Documentaries' 'Classic Movies'
 'Stand-Up' 'Cult Movies' 'Thrillers' 'Horror Movies' 'Docuseries']

In [90]:
# Count number of short action movies less than 90 minutes released in the 1990s
short_movie_count = len(movies_1990s[(movies_1990s['duration'] < 90) & (movies_1990s['genre'] == 'Action')])
print(short_movie_count)

7